title = "Lazomi"
author = "Lara Sitruk"
base_url = "https://lazomi.studio"

[paths]
content = "content"
output = "public"
static = "static"
templates = "templates"

[nav]
nested = false  # Show child pages under sections
